-- Create the audit table to track changes in the appointment table
CREATE TABLE appointment_audit (
  audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id  NUMBER NOT NULL,
  operation_type  VARCHAR2(10) NOT NULL, -- INSERT, UPDATE, DELETE
  performed_by    VARCHAR2(150) NOT NULL,
  action_time     TIMESTAMP   NOT NULL,
  old_status      VARCHAR2(20),
  new_status      VARCHAR2(20),
  cancel_reason   VARCHAR2(255)
);

-- Verify the structure
DESC appointment_audit;
